name: Generate RSS

on:
  schedule:
    - cron: "0 0 * * *" # Every day
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Generate RSS
        run: node script.js

      - name: Commit and push if there are changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          if [ -n "$(git status rss/*.rss.xml --porcelain)" ]; then
            git add rss/*.rss.xml
            git commit -m "feed: update RSS feeds"
            git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit."
          fi
